from enum import IntEnum, IntFlag
from typing import Any, Callable, Dict, Iterator, List, Optional, Sequence, Tuple, Union

# Placeholder subset of the ST 4200 `sublime` module.
# Written with 3.8-compatible syntax because that is the interpreter ST 4200 embeds.

Point = int
Value = Union[None, bool, str, int, float, List["Value"], Dict[str, "Value"]]
Dip = float
CommandArgs = Optional[Dict[str, Value]]

class HoverZone(IntEnum):
    TEXT = 1
    GUTTER = 2
    MARGIN = 3

class NewFileFlags(IntFlag):
    NONE = 0
    ENCODED_POSITION = 1
    TRANSIENT = 4
    FORCE_GROUP = 8
    SEMI_TRANSIENT = 16
    ADD_TO_SELECTION = 32
    REPLACE_MRU = 64
    CLEAR_TO_RIGHT = 128
    FORCE_CLONE = 256

class RegionFlags(IntFlag):
    NONE = 0
    DRAW_EMPTY = 1
    HIDE_ON_MINIMAP = 2
    DRAW_EMPTY_AS_OVERWRITE = 4
    PERSISTENT = 16
    DRAW_NO_FILL = 32
    HIDDEN = 128
    DRAW_NO_OUTLINE = 256
    DRAW_SOLID_UNDERLINE = 512
    DRAW_STIPPLED_UNDERLINE = 1024
    DRAW_SQUIGGLY_UNDERLINE = 2048
    NO_UNDO = 8192

class Region:
    a: Point
    b: Point
    xpos: Dip
    def __init__(self, a: Point, b: Optional[Point] = ..., xpos: Dip = ...) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, v: Union["Region", Point]) -> bool: ...
    def to_tuple(self) -> Tuple[Point, Point]: ...
    def empty(self) -> bool: ...
    def begin(self) -> Point: ...
    def end(self) -> Point: ...
    def size(self) -> int: ...
    def contains(self, x: Union["Region", Point]) -> bool: ...
    def cover(self, region: "Region") -> "Region": ...
    def intersection(self, region: "Region") -> "Region": ...
    def intersects(self, region: "Region") -> bool: ...

class Selection:
    view_id: int
    def __init__(self, id: int) -> None: ...
    def __iter__(self) -> Iterator[Region]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Region: ...
    def __delitem__(self, index: int) -> None: ...
    def __contains__(self, region: Region) -> bool: ...
    def is_valid(self) -> bool: ...
    def clear(self) -> None: ...
    def add(self, x: Union[Region, Point]) -> None: ...
    def add_all(self, regions: Sequence[Union[Region, Point]]) -> None: ...
    def subtract(self, region: Region) -> None: ...

class Settings:
    settings_id: int
    def __init__(self, id: int) -> None: ...
    def get(self, key: str, default: Value = ...) -> Value: ...
    def has(self, key: str) -> bool: ...
    def set(self, key: str, value: Value) -> None: ...
    def erase(self, key: str) -> None: ...
    def add_on_change(self, tag: str, callback: Callable[[], None]) -> None: ...
    def clear_on_change(self, tag: str) -> None: ...

class Edit:
    edit_token: int
    def __init__(self, token: int) -> None: ...

class View:
    view_id: int
    def __init__(self, id: int) -> None: ...
    def __bool__(self) -> bool: ...
    def id(self) -> int: ...
    def is_valid(self) -> bool: ...
    def window(self) -> Optional["Window"]: ...
    def file_name(self) -> Optional[str]: ...
    def name(self) -> str: ...
    def set_name(self, name: str) -> None: ...
    def is_dirty(self) -> bool: ...
    def is_read_only(self) -> bool: ...
    def is_scratch(self) -> bool: ...
    def size(self) -> int: ...
    def settings(self) -> Settings: ...
    def substr(self, x: Union[Region, Point]) -> str: ...
    def insert(self, edit: Edit, pt: Point, text: str) -> int: ...
    def erase(self, edit: Edit, region: Region) -> None: ...
    def replace(self, edit: Edit, region: Region, text: str) -> None: ...
    def sel(self) -> Selection: ...
    def line(self, x: Union[Region, Point]) -> Region: ...
    def full_line(self, x: Union[Region, Point]) -> Region: ...
    def word(self, x: Union[Region, Point]) -> Region: ...
    def rowcol(self, tp: Point) -> Tuple[int, int]: ...
    def text_point(self, row: int, col: int, *, clamp_column: bool = ...) -> Point: ...
    def find(self, pattern: str, start_pt: Point, flags: int = ...) -> Region: ...
    def find_all(self, pattern: str, flags: int = ...) -> List[Region]: ...
    def run_command(self, cmd: str, args: CommandArgs = ...) -> None: ...
    def add_regions(
        self,
        key: str,
        regions: Sequence[Region],
        scope: str = ...,
        icon: str = ...,
        flags: RegionFlags = ...,
    ) -> None: ...
    def get_regions(self, key: str) -> List[Region]: ...
    def erase_regions(self, key: str) -> None: ...
    def show(self, location: Union[Region, Selection, Point], show_surrounds: bool = ...) -> None: ...
    def show_popup(
        self,
        content: str,
        flags: int = ...,
        location: Point = ...,
        max_width: Dip = ...,
        max_height: Dip = ...,
        on_navigate: Optional[Callable[[str], None]] = ...,
        on_hide: Optional[Callable[[], None]] = ...,
    ) -> None: ...
    def hide_popup(self) -> None: ...

class Sheet:
    sheet_id: int
    def __init__(self, id: int) -> None: ...
    def id(self) -> int: ...
    def window(self) -> Optional["Window"]: ...
    def view(self) -> Optional[View]: ...

class Window:
    window_id: int
    def __init__(self, id: int) -> None: ...
    def __bool__(self) -> bool: ...
    def id(self) -> int: ...
    def is_valid(self) -> bool: ...
    def active_view(self) -> Optional[View]: ...
    def views(self, *, include_transient: bool = ...) -> List[View]: ...
    def new_file(self, flags: NewFileFlags = ..., syntax: str = ...) -> View: ...
    def open_file(self, fname: str, flags: NewFileFlags = ..., group: int = ...) -> View: ...
    def find_open_file(self, fname: str, group: int = ...) -> Optional[View]: ...
    def focus_view(self, view: View) -> None: ...
    def folders(self) -> List[str]: ...
    def project_file_name(self) -> Optional[str]: ...
    def settings(self) -> Settings: ...
    def run_command(self, cmd: str, args: CommandArgs = ...) -> None: ...
    def status_message(self, msg: str) -> None: ...
    def show_quick_panel(
        self,
        items: Union[Sequence[str], Sequence[Sequence[str]]],
        on_select: Callable[[int], None],
        flags: int = ...,
        selected_index: int = ...,
        on_highlight: Optional[Callable[[int], None]] = ...,
        placeholder: Optional[str] = ...,
    ) -> None: ...
    def show_input_panel(
        self,
        caption: str,
        initial_text: str,
        on_done: Optional[Callable[[str], None]],
        on_change: Optional[Callable[[str], None]],
        on_cancel: Optional[Callable[[], None]],
    ) -> View: ...

def version() -> str: ...
def platform() -> str: ...
def arch() -> str: ...
def packages_path() -> str: ...
def cache_path() -> str: ...
def executable_path() -> str: ...
def active_window() -> Window: ...
def windows() -> List[Window]: ...
def status_message(msg: str) -> None: ...
def message_dialog(msg: str) -> None: ...
def error_message(msg: str) -> None: ...
def ok_cancel_dialog(msg: str, ok_title: str = ..., title: str = ...) -> bool: ...
def load_settings(base_name: str) -> Settings: ...
def save_settings(base_name: str) -> None: ...
def set_timeout(f: Callable[[], Any], timeout_ms: int = ...) -> None: ...
def set_timeout_async(f: Callable[[], Any], timeout_ms: int = ...) -> None: ...
def load_resource(name: str) -> str: ...
def load_binary_resource(name: str) -> bytes: ...
def find_resources(pattern: str) -> List[str]: ...
def decode_value(data: str) -> Value: ...
def encode_value(val: Value, pretty: bool = ..., update_text: Optional[str] = ...) -> str: ...
def expand_variables(val: Value, variables: Dict[str, str]) -> Value: ...
def run_command(cmd: str, args: CommandArgs = ...) -> None: ...
