# This file is generated by tools/generate_stubs.py -- do not edit.
# Source: references/python38/sublime_types.py (Sublime Text build 4200).

from __future__ import annotations

from typing import Any
from typing_extensions import TypeAlias
from sublime import CompletionItem, KindId

DIP: TypeAlias = float
Vector: TypeAlias = tuple[DIP, DIP]
Point: TypeAlias = int
Value: TypeAlias = bool | str | int | float | list[Value] | dict[str, Value] | None
CommandArgs: TypeAlias = dict[str, Value] | None
Kind: TypeAlias = tuple[KindId, str, str]
Event: TypeAlias = dict[str, Any]
CompletionValue: TypeAlias = str | tuple[str, str] | CompletionItem
