# This file is generated by tools/generate_stubs.py -- do not edit.
# Source: references/python38/sublime_types.py (Sublime Text build 4200).

from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import TypeAlias
from sublime import CompletionItem, KindId

DIP: TypeAlias = float
Vector: TypeAlias = Tuple[DIP, DIP]
Point: TypeAlias = int
Value: TypeAlias = Union[bool, str, int, float, List["Value"], Dict[str, "Value"], None]
CommandArgs: TypeAlias = Optional[Dict[str, Value]]
Kind: TypeAlias = Tuple[KindId, str, str]
Event: TypeAlias = Dict[str, Any]
CompletionValue: TypeAlias = Union[str, Tuple[str, str], CompletionItem]
