from typing import Any, Dict, List, Optional, Tuple

import sublime

# Placeholder subset of the ST 4200 `sublime_plugin` module.

class CommandInputHandler:
    def name(self) -> str: ...
    def placeholder(self) -> str: ...
    def initial_text(self) -> str: ...
    def preview(self, arg: Any) -> Any: ...
    def validate(self, arg: Any) -> bool: ...
    def cancel(self) -> None: ...
    def confirm(self, arg: Any) -> None: ...
    def next_input(self, args: Dict[str, Any]) -> Optional["CommandInputHandler"]: ...
    def want_event(self) -> bool: ...

class TextInputHandler(CommandInputHandler): ...

class ListInputHandler(CommandInputHandler):
    def list_items(self) -> Any: ...

class Command:
    def name(self) -> str: ...
    def is_enabled(self) -> bool: ...
    def is_visible(self) -> bool: ...
    def is_checked(self) -> bool: ...
    def description(self) -> Optional[str]: ...
    def want_event(self) -> bool: ...
    def input(self, args: Dict[str, Any]) -> Optional[CommandInputHandler]: ...
    def input_description(self) -> str: ...
    # `run` is deliberately not declared here: Sublime Text invokes it dynamically with
    # command-specific keyword arguments, so any base signature would either reject
    # valid subclasses or erase their argument types.

class ApplicationCommand(Command): ...

class WindowCommand(Command):
    window: sublime.Window
    def __init__(self, window: sublime.Window) -> None: ...

class TextCommand(Command):
    view: sublime.View
    def __init__(self, view: sublime.View) -> None: ...
    def run(self, edit: sublime.Edit) -> None: ...

class EventListener:
    def on_new(self, view: sublime.View) -> None: ...
    def on_activated(self, view: sublime.View) -> None: ...
    def on_deactivated(self, view: sublime.View) -> None: ...
    def on_load(self, view: sublime.View) -> None: ...
    def on_pre_close(self, view: sublime.View) -> None: ...
    def on_close(self, view: sublime.View) -> None: ...
    def on_pre_save(self, view: sublime.View) -> None: ...
    def on_post_save(self, view: sublime.View) -> None: ...
    def on_modified(self, view: sublime.View) -> None: ...
    def on_selection_modified(self, view: sublime.View) -> None: ...
    def on_hover(self, view: sublime.View, point: sublime.Point, hover_zone: sublime.HoverZone) -> None: ...
    def on_query_context(
        self, view: sublime.View, key: str, operator: int, operand: Any, match_all: bool
    ) -> Optional[bool]: ...
    def on_query_completions(
        self, view: sublime.View, prefix: str, locations: List[sublime.Point]
    ) -> Any: ...
    def on_text_command(
        self, view: sublime.View, command_name: str, args: sublime.CommandArgs
    ) -> Optional[Tuple[str, sublime.CommandArgs]]: ...
    def on_window_command(
        self, window: sublime.Window, command_name: str, args: sublime.CommandArgs
    ) -> Optional[Tuple[str, sublime.CommandArgs]]: ...

class ViewEventListener:
    view: sublime.View
    def __init__(self, view: sublime.View) -> None: ...
    @classmethod
    def is_applicable(cls, settings: sublime.Settings) -> bool: ...
    @classmethod
    def applies_to_primary_view_only(cls) -> bool: ...

class TextChangeListener:
    buffer: Any
    def __init__(self) -> None: ...
    @classmethod
    def is_applicable(cls, buffer: Any) -> bool: ...
    def on_text_changed(self, changes: List[Any]) -> None: ...
